### ISSUE TITLE
Error "invalid value: integer" when running inside a podman/docker container

### ISSUE THREAD

**Issue by cielonet** [br0kej/bin2ml#4]
**Modified Cargo.toml**
```toml
[dependencies]
r2pipe = "0.7.0"
```

**Modified Dockerfile**
```bash
podman build . -t bin2ml
```

```Dockerfile
FROM rust as builder

WORKDIR /opt/bin2ml

RUN env USER=root cargo init .

COPY Cargo.toml .
COPY src /opt/bin2ml/src

RUN cd /opt/bin2ml && \
    cargo install --locked --path . && \
    rm -rf /opt/bin2ml && \
    rm -rf /usr/local/cargo/registry

FROM rust

COPY --from=builder /usr/local/cargo/bin/bin2ml /usr/local/cargo/bin/bin2ml

RUN git clone https://github.com/radareorg/radare2 radare2
RUN cd radare2 ; sys/install.sh

CMD bin2ml --version
```
**Executed from host**
```bash
podman run --rm -it -v `pwd`/test-files:/data:z localhost/bin2ml bash
```

```bash
root@5b7b60c1c6a0:/data# RUST_BACKTRACE=1 bin2ml extract --fpath /bin/true --output-dir out --mode reg
[2023-12-06T03:25:11Z INFO  bin2ml] Creating extraction job
[2023-12-06T03:25:11Z INFO  bin2ml] Single file found
[2023-12-06T03:25:11Z INFO  bin2ml] Extraction Job Type: Register Behaviour
[2023-12-06T03:25:11Z INFO  bin2ml::extract] Starting register behaviour extraction
[2023-12-06T03:25:11Z INFO  bin2ml::extract] Getting function information from binary
[2023-12-06T03:25:11Z INFO  bin2ml::extract] Executing aeafj for each function
thread 'main' panicked at src/extract.rs:311:45:
Unable to convert to JSON object!: Error("invalid value: integer `18446744073709551615`, expected i64", line: 1, column: 2449)
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

**Comment by cielonet** [comment]
I know I modified to use 0.7.0 but I confirmed 0.6.0 also gets same error!
```bash
root@362df194b334:/data# mkdir out
root@362df194b334:/data# bin2ml extract --fpath /bin/true --output-dir out --mode cfg
[2023-12-06T03:43:37Z INFO  bin2ml] Creating extraction job
[2023-12-06T03:43:37Z INFO  bin2ml] Single file found
[2023-12-06T03:43:37Z INFO  bin2ml] Extraction Job Type: CFG
[2023-12-06T03:43:37Z INFO  bin2ml::extract] out/true_cfg.json not found. Continuing processing.
[2023-12-06T03:43:37Z INFO  bin2ml::extract] Executing agfj @@f on /bin/true
[2023-12-06T03:43:37Z INFO  bin2ml::extract] Closing r2p process for /bin/true
[2023-12-06T03:43:37Z INFO  bin2ml::extract] Starting JSON fixup for /bin/true
[2023-12-06T03:43:37Z INFO  bin2ml::extract] JSON fixup finished for /bin/true
[2023-12-06T03:43:37Z INFO  bin2ml] Extraction complete for /bin/true
root@362df194b334:/data# bin2ml extract --fpath /bin/true --output-dir out --mode reg
[2023-12-06T03:43:42Z INFO  bin2ml] Creating extraction job
[2023-12-06T03:43:42Z INFO  bin2ml] Single file found
[2023-12-06T03:43:42Z INFO  bin2ml] Extraction Job Type: Register Behaviour
[2023-12-06T03:43:42Z INFO  bin2ml::extract] Starting register behaviour extraction
[2023-12-06T03:43:42Z INFO  bin2ml::extract] Getting function information from binary
[2023-12-06T03:43:42Z INFO  bin2ml::extract] Executing aeafj for each function
thread 'main' panicked at src/extract.rs:311:45:
Unable to convert to JSON object!: Error("invalid value: integer `18446744073709551615`, expected i64", line: 1, column: 2449)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by cielonet** [comment]
Modified extract.rs i64 to u64 and it works! But I'm not sure if this is the intended result from this tool given negative values will not be captured perhaps?

```rust
// Structs related to AEAFJ
#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AEAFJRegisterBehaviour {
    #[serde(rename = "A")]
    pub a: Vec<String>,
    #[serde(rename = "I")]
    pub i: Vec<String>,
    #[serde(rename = "R")]
    pub r: Vec<String>,
    #[serde(rename = "W")]
    pub w: Vec<String>,
    #[serde(rename = "V")]
    pub v: Vec<String>,
    #[serde(rename = "N")]
    #[serde(default)]
    pub n: Vec<String>,
    #[serde(rename = "@R")]
    #[serde(default)]
    pub r2: Vec<u64>,
    #[serde(rename = "@W")]
    #[serde(default)]
    pub w2: Vec<u64>,
}

```
```bash
root@80a0d156bece:/data# bin2ml extract --fpath /bin/true --output-dir out --mode reg
[2023-12-06T11:41:35Z INFO  bin2ml] Creating extraction job
[2023-12-06T11:41:35Z INFO  bin2ml] Single file found
[2023-12-06T11:41:35Z INFO  bin2ml] Extraction Job Type: Register Behaviour
[2023-12-06T11:41:35Z INFO  bin2ml::extract] Starting register behaviour extraction
[2023-12-06T11:41:36Z INFO  bin2ml::extract] Getting function information from binary
[2023-12-06T11:41:36Z INFO  bin2ml::extract] Executing aeafj for each function
[2023-12-06T11:41:36Z INFO  bin2ml::extract] All functions processed
[2023-12-06T11:41:36Z INFO  bin2ml::extract] r2p closed
[2023-12-06T11:41:36Z INFO  bin2ml::extract] Writing extracted data to file
[2023-12-06T11:41:36Z INFO  bin2ml] Extraction complete for /bin/true
```

**Comment by br0kej** [comment]
The dtype used within r2 is a u64 so definitely a good idea mirroring it! The change has been pushed to main
